# Generated by Django 5.2.7 on 2025-10-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Укажите заголовок статьи",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Разместите содержимое стать",
                        verbose_name="Содержимое статьи",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="Подходящая картинка",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("publication_attribute", models.BooleanField(default=True)),
                ("numbers_views", models.IntegerField()),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["heading", "create_at", "numbers_views"],
            },
        ),
    ]
