# Generated by Django 5.2.7 on 2025-10-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="numbers_views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_attribute",
            field=models.BooleanField(default=False),
        ),
    ]
