# Generated by Django 5.2.7 on 2025-11-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_owner_product_publication_attribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name", "purchase_price"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукты",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
